# Generated by Django 5.0.7 on 2024-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attended_class',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
